### ISSUE TITLE
CString::new("foo").unwrap().as_ptr() gives a dangling pointer

### ISSUE THREAD

**Issue by Lokathor** [glowcoil/raw-gl-context#3]
In many places you use this phrase. It gives a dangling pointer because the CString is dropped at the end of the expression. You need to bind the CString to a local variable after the unwrap, and then call as_ptr on that local variable.

**Comment by micahrj** [comment]
The Rust book actually [states that this is perfectly fine](https://doc.rust-lang.org/1.48.0/reference/destructors.html#temporary-scopes), since the `CString` will live for the duration of the statement containing it:

> Apart from lifetime extension, the temporary scope of an expression is the smallest scope that contains the expression and is for one of the following:
>
> - The entire function body.
> - A statement.
> - The body of a if, while or loop expression.
> - The else block of an if expression.
> - The condition expression of an if or while expression, or a match guard.
> - The expression for a match arm.
> - The second operand of a lazy boolean expression.

And everywhere this idiom occurs in `raw-gl-context`, the pointer is not used beyond the duration of the containing statement (where it is, I [assign it to a local like you suggest](https://github.com/glowcoil/raw-gl-context/blob/b242b9ca4f26aadd20d91dc4a84f539093e217bc/src/win.rs#L276-L284)).

That being said, I can get behind making this change for style/clarity reasons even if it is not necessary for correctness.

**Comment by Lokathor** [comment]
Ah, some interesting fine detail there.
